name: build-pr
run-name: "build ${{ inputs.packages }} from ${{ inputs.repo }}#${{ inputs.pr-number }}"

permissions: {}

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "GitHub repository (owner/name)"
        required: true
        type: string

      pr-number:
        description: "Pull Request number"
        required: true
        type: number

      packages:
        description: "Nix packages or flake attributes to build"
        required: true
        type: string

      x86_64-linux:
        description: "Build on x86_64-linux"
        required: true
        type: boolean
        default: true

      aarch64-linux:
        description: "Build on aarch64-linux"
        required: true
        type: boolean
        default: true

      x86_64-darwin:
        description: "Build on x86_64-darwin"
        required: true
        type: choice
        default: yes_sandbox_relaxed
        options:
          - "no"
          - yes_sandbox_false
          - yes_sandbox_relaxed
          - yes_sandbox_true

      aarch64-darwin:
        description: "Build on aarch64-darwin"
        required: true
        type: choice
        default: yes_sandbox_relaxed
        options:
          - "no"
          - yes_sandbox_false
          - yes_sandbox_relaxed
          - yes_sandbox_true

      upterm:
        description: "Start upterm session after nix build"
        required: true
        type: boolean
        default: false

      post-result:
        description: "Post Result"
        required: true
        type: boolean
        default: true

      upload-cachix:
        description: "Upload to Cachix"
        required: true
        type: boolean
        default: true

jobs:
  check-creds:
    runs-on: ubuntu-latest
    outputs:
      gh_token: ${{ steps.check-creds.outputs.gh_token }}
      cachix: ${{ steps.check-creds.outputs.cachix }}
      tg: ${{ steps.check-creds.outputs.tg }}
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /.github/actions
            /build-pr

      - name: setup nu
        uses: ./.github/actions/setup-nu

      - name: check credentials
        id: check-creds
        run: nu build-pr/check-creds.nu
        env:
          GH_TOKEN_SECRET: ${{ secrets.GH_TOKEN }}
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}

  prepare:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.prepare.outputs.packages }}
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /.github/actions
            /build-pr

      - name: setup nu
        uses: ./.github/actions/setup-nu

      - name: parse packages
        id: prepare
        run: nu build-pr/prepare.nu
        env:
          INPUTS: ${{ toJSON(github.event.inputs) }}

  build:
    name: build-${{ matrix.system }}-${{ matrix.package }}
    permissions:
      actions: read
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux
          - x86_64-darwin
          - aarch64-darwin
        package: ${{ fromJson(needs.prepare.outputs.packages) }}
        exclude:
          - system: ${{ !inputs.x86_64-linux && 'x86_64-linux' || '' }}
          - system: ${{ !inputs.aarch64-linux && 'aarch64-linux' || '' }}
          - system: ${{ inputs.x86_64-darwin == 'no' && 'x86_64-darwin' || '' }}
          - system: ${{ inputs.aarch64-darwin == 'no' && 'aarch64-darwin' || '' }}

    runs-on: >-
      ${{ (matrix.system == 'x86_64-linux' && 'ubuntu-latest')
      || (matrix.system == 'aarch64-linux' && 'ubuntu-24.04-arm')
      || (matrix.system == 'x86_64-darwin' && 'macos-latest')
      || (matrix.system == 'aarch64-darwin' && 'macos-latest') }}

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /.github/actions
            /build-pr

      - name: setup nu
        uses: ./.github/actions/setup-nu

      - name: Free Disk Space
        if: runner.os == 'Linux'
        uses: jlumbroso/free-disk-space@main

      - name: Add swap
        if: runner.os == 'Linux'
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 15

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          extra-nix-config: ${{ vars.EXTRA_NIX_CONFIG }}
          system: ${{ matrix.system }}
          sandbox: ${{
            (matrix.system == 'x86_64-darwin' && inputs.x86_64-darwin == 'yes_sandbox_false'
            || matrix.system == 'aarch64-darwin' && inputs.aarch64-darwin == 'yes_sandbox_false') && 'false'
            || (matrix.system == 'x86_64-darwin' && inputs.x86_64-darwin == 'yes_sandbox_relaxed'
            || matrix.system == 'aarch64-darwin' && inputs.aarch64-darwin == 'yes_sandbox_relaxed') && 'relaxed'
            || 'true' }}

      - name: Checkout PR
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.repo }}
          ref: refs/pull/${{ inputs.pr-number }}/head
          fetch-depth: 1
          path: src

      - name: Nix build
        id: build-nu
        continue-on-error: true
        run: nu build-pr/build.nu
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MATRIX_SYSTEM: ${{ matrix.system }}
          MATRIX_PACKAGE: ${{ matrix.package }}

      - name: Start upterm session
        if: ${{ inputs.upterm }}
        uses: owenthereal/action-upterm@v1
        with:
          limit-access-to-actor: true

      - uses: actions/upload-artifact@v7
        with:
          name: build_report_${{ matrix.system }}_${{ matrix.package }}.json
          path: build_report_${{ matrix.system }}_${{ matrix.package }}.json
          if-no-files-found: error

      - name: Upload to Cachix
        if: >-
          ${{
            matrix.system == 'x86_64-linux'
            && inputs.upload-cachix
            && needs.check-creds.outputs.cachix == 'true'
            && steps.build-nu.outputs.successful == 'true'
          }}
        working-directory: src
        env:
          CACHIX_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        continue-on-error: true
        run: |
          nix run nixpkgs#cachix -- authtoken "$CACHIX_TOKEN"
          nix run nixpkgs#cachix -- push loneros $(nix path-info .#${{ matrix.package }})

  report:
    runs-on: ubuntu-latest
    needs: [build, check-creds]
    if: ${{ !cancelled() && inputs.post-result }}
    outputs:
      success: ${{ steps.report.outputs.success }}

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /.github/actions
            /build-pr

      - name: setup nu
        uses: ./.github/actions/setup-nu

      - uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: Generate and publish report
        id: report
        run: nu build-pr/report.nu
        env:
          INPUTS: ${{ toJSON(github.event.inputs) }}
          TG_ENABLED: ${{ needs.check-creds.outputs.tg }}

      - uses: actions/upload-artifact@v7
        with:
          name: report.md
          path: report.md
          archive: false
          if-no-files-found: error

      - name: Upload TG notification
        if: needs.check-creds.outputs.tg == 'true'
        uses: actions/upload-artifact@v7
        with:
          name: telegram-notification.txt
          path: telegram-notification.txt
          if-no-files-found: error

  post-result:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: [report, check-creds]
    if: ${{ !cancelled() && inputs.post-result }}
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /.github/actions
            /build-pr

      - name: setup nu
        uses: ./.github/actions/setup-nu

      - uses: actions/download-artifact@v8
        with:
          name: report.md

      - name: Post comment and manage labels
        if: needs.check-creds.outputs.gh_token == 'true'
        run: nu build-pr/post-result.nu
        env:
          INPUTS: ${{ toJSON(github.event.inputs) }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN_ENABLED: ${{ needs.check-creds.outputs.gh_token }}
          BUILD_SUCCESS: ${{ needs.report.outputs.success }}

      - name: Download TG notification
        if: needs.check-creds.outputs.tg == 'true'
        uses: actions/download-artifact@v8
        with:
          name: telegram-notification.txt

      - name: Send Telegram notification
        if: needs.check-creds.outputs.tg == 'true'
        uses: appleboy/telegram-action@v1.0.1
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message_file: telegram-notification.txt
          format: html
