name: test

permissions: {}

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /.github/actions
            /build-pr

      - name: setup nu
        uses: ./.github/actions/setup-nu

      - name: run build-pr tests
        run: nu build-pr/test.nu
